#!/usr/bin/env python3
"""Find conservative code-cleanup leads without executing project code."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
from collections import defaultdict
from datetime import UTC, datetime
from pathlib import Path, PurePath
from typing import Any

from artifact_safety import ArtifactSafetyError, publish_new_artifacts, validate_artifact_outputs

SOURCE_SUFFIXES = {".cjs", ".js", ".jsx", ".mjs", ".py", ".ts", ".tsx"}
TEXT_SUFFIXES = SOURCE_SUFFIXES | {
    ".css",
    ".html",
    ".json",
    ".md",
    ".scss",
    ".toml",
    ".yaml",
    ".yml",
}
EXCLUDED_DIRECTORIES = {
    ".git",
    ".hg",
    ".mypy_cache",
    ".next",
    ".nuxt",
    ".pytest_cache",
    ".ruff_cache",
    ".svn",
    ".svelte-kit",
    ".venv",
    "__pycache__",
    "build",
    "coverage",
    "dist",
    "node_modules",
    "out",
    "outputs",
    "target",
    "vendor",
    "venv",
}
ENTRY_FILENAMES = {
    "__main__.py",
    "app.js",
    "app.ts",
    "app.tsx",
    "asgi.py",
    "cli.js",
    "cli.ts",
    "conftest.py",
    "index.js",
    "index.jsx",
    "index.ts",
    "index.tsx",
    "main.js",
    "main.jsx",
    "main.ts",
    "main.tsx",
    "manage.py",
    "server.js",
    "server.ts",
    "wsgi.py",
}
CONVENTION_DIRECTORIES = {
    "commands",
    "fixtures",
    "jobs",
    "management",
    "migrations",
    "pages",
    "plugins",
    "routes",
    "scripts",
    "seeds",
    "stories",
    "workers",
}
GENERATED_MARKERS = ("auto-generated", "autogenerated", "do not edit", "generated file")
CATEGORY_ORDER = {
    "orphan-file": 0,
    "unused-dependency": 1,
    "unused-export": 2,
    "duplicate-file": 3,
    "commented-code": 4,
}


def timestamp() -> str:
    return datetime.now(UTC).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def relative_path(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def source_line_count(text: str) -> int:
    return len(text.splitlines()) if text else 0


def read_text(path: Path, maximum_size: int = 2_000_000) -> str:
    try:
        if path.stat().st_size > maximum_size:
            return ""
        return path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""


def walk_files(root: Path, suffixes: set[str]) -> list[Path]:
    files: list[Path] = []
    for directory, directory_names, file_names in os.walk(root, followlinks=False):
        directory_names[:] = sorted(
            name for name in directory_names if name not in EXCLUDED_DIRECTORIES
        )
        base = Path(directory)
        for name in sorted(file_names):
            path = base / name
            if path.is_symlink():
                continue
            if path.suffix.lower() in suffixes and path.is_file():
                files.append(path)
    return files


def local_path(root: Path, base: Path, value: str) -> str | None:
    cleaned = value.split("?", 1)[0]
    if not cleaned or Path(cleaned).is_absolute():
        return None
    candidate = (base / cleaned).resolve()
    if candidate == root or root not in candidate.parents or not candidate.exists():
        return None
    return relative_path(candidate, root)


def nested_local_paths(value: Any, root: Path, base: Path) -> set[str]:
    if isinstance(value, str):
        result = local_path(root, base, value)
        return {result} if result else set()
    if isinstance(value, list):
        return set().union(*(nested_local_paths(item, root, base) for item in value))
    if isinstance(value, dict):
        return set().union(*(nested_local_paths(item, root, base) for item in value.values()))
    return set()


def package_information(root: Path) -> tuple[set[str], list[tuple[str, str, str]], set[Path]]:
    entrypoints: set[str] = set()
    dependencies: list[tuple[str, str, str]] = []
    manifests: set[Path] = set()
    for path in walk_files(root, {".json"}):
        if path.name != "package.json":
            continue
        text = read_text(path)
        try:
            package = json.loads(text)
        except json.JSONDecodeError:
            continue
        manifests.add(path.resolve())
        manifest_relative = relative_path(path, root)
        for field in ("main", "module", "browser", "bin", "exports"):
            entrypoints.update(nested_local_paths(package.get(field), root, path.parent))
        scripts = package.get("scripts")
        if isinstance(scripts, dict):
            for command in scripts.values():
                if not isinstance(command, str):
                    continue
                for match in re.findall(
                    r"(?:^|\s)((?:\.?/?[A-Za-z0-9_./-]+)\.(?:[cm]?[jt]sx?|py))(?:\s|$)",
                    command,
                ):
                    candidate = local_path(root, path.parent, f"./{match.lstrip('./')}")
                    if candidate:
                        entrypoints.add(candidate)
        for section in ("dependencies", "devDependencies", "optionalDependencies", "peerDependencies"):
            declared = package.get(section)
            if isinstance(declared, dict):
                dependencies.extend((name, section, manifest_relative) for name in declared)
    return entrypoints, dependencies, manifests


def is_protected_path(relative: str, text: str, entrypoints: set[str]) -> bool:
    path = PurePath(relative)
    name = path.name
    lowered_parts = {part.lower() for part in path.parts[:-1]}
    if relative in entrypoints or name in ENTRY_FILENAMES:
        return True
    if name == "__init__.py" or name.endswith(".d.ts"):
        return True
    if any(part in CONVENTION_DIRECTORIES for part in lowered_parts):
        return True
    if name.startswith(("next.config.", "vite.config.", "webpack.config.", "rollup.config.")):
        return True
    if name.startswith(("test_", "test-")) or ".test." in name or ".spec." in name:
        return True
    if name in {"page.ts", "page.tsx", "layout.ts", "layout.tsx", "route.js", "route.ts"}:
        return True
    return any(marker in text[:1_000].lower() for marker in GENERATED_MARKERS)


def javascript_specifiers(text: str) -> list[str]:
    patterns = (
        r"\b(?:import|export)\s+(?:[^;\n]*?\s+from\s+)?['\"]([^'\"]+)['\"]",
        r"\brequire\s*\(\s*['\"]([^'\"]+)['\"]\s*\)",
        r"\bimport\s*\(\s*['\"]([^'\"]+)['\"]\s*\)",
    )
    return [specifier for pattern in patterns for specifier in re.findall(pattern, text)]


def package_name(specifier: str) -> str:
    if specifier.startswith("@"):
        return "/".join(specifier.split("/")[:2])
    return specifier.split("/", 1)[0]


def resolve_javascript_import(source: Path, specifier: str, source_paths: set[Path]) -> Path | None:
    if not specifier.startswith("."):
        return None
    base = (source.parent / specifier).resolve()
    possibilities = [base]
    if not base.suffix:
        possibilities.extend(base.with_suffix(suffix) for suffix in SOURCE_SUFFIXES - {".py"})
        possibilities.extend(base / f"index{suffix}" for suffix in SOURCE_SUFFIXES - {".py"})
    return next((path for path in possibilities if path in source_paths), None)


def python_module_name(path: Path, root: Path) -> str:
    parts = list(path.relative_to(root).with_suffix("").parts)
    if parts[-1] == "__init__":
        parts.pop()
    return ".".join(parts)


def python_import_targets(source: Path, text: str, root: Path, module_paths: dict[str, Path]) -> set[Path]:
    targets: set[Path] = set()
    source_module = python_module_name(source, root)
    source_parts = source_module.split(".") if source_module else []
    package_parts = source_parts if source.name == "__init__.py" else source_parts[:-1]

    for raw in re.findall(r"^\s*import\s+([\w.,\s]+)", text, flags=re.MULTILINE):
        for item in raw.split(","):
            module = item.strip().split(" as ", 1)[0].strip()
            if module in module_paths:
                targets.add(module_paths[module])

    for raw_module, imported in re.findall(
        r"^\s*from\s+([.\w]+)\s+import\s+([\w*,\s]+)", text, flags=re.MULTILINE
    ):
        dot_count = len(raw_module) - len(raw_module.lstrip("."))
        suffix = raw_module.lstrip(".")
        if dot_count:
            base = package_parts[: max(0, len(package_parts) - dot_count + 1)]
            module = ".".join(base + ([suffix] if suffix else []))
        else:
            module = suffix
        if module in module_paths:
            targets.add(module_paths[module])
        for name in imported.split(","):
            child = name.strip().split(" as ", 1)[0].strip()
            if child and child != "*" and f"{module}.{child}" in module_paths:
                targets.add(module_paths[f"{module}.{child}"])
    return targets


def normalized_source(text: str) -> str:
    return "\n".join(line.strip() for line in text.splitlines() if line.strip())


def make_candidate(
    category: str,
    subject: str,
    path: str | None,
    confidence: str,
    risk: str,
    proof_eligible: bool,
    loc: int,
    size: int,
    evidence: list[str],
    caveats: list[str],
    line: int | None = None,
) -> dict[str, Any]:
    result: dict[str, Any] = {
        "category": category,
        "subject": subject,
        "path": path,
        "confidence": confidence,
        "initial_status": "REVIEW",
        "risk": risk,
        "proof_eligible": proof_eligible,
        "loc": loc,
        "bytes": size,
        "evidence": evidence,
        "caveats": caveats,
    }
    if line is not None:
        result["line"] = line
    return result


def referenced_outside_file(relative: str, path: Path, texts: dict[Path, str]) -> list[str]:
    candidates = {relative, path.name, path.stem}
    outside = "\n".join(text for other_path, text in texts.items() if other_path != path)
    mentions: list[str] = []
    for token in sorted(candidates, key=len, reverse=True):
        if len(token) >= 4 and token in outside:
            mentions.append(token)
    return mentions


def analyze(project_root: Path) -> dict[str, Any]:
    root = project_root.resolve()
    if not root.is_dir():
        raise ValueError(f"Project root is not a directory: {root}")

    source_files = walk_files(root, SOURCE_SUFFIXES)
    text_files = walk_files(root, TEXT_SUFFIXES)
    texts = {path.resolve(): read_text(path) for path in text_files}
    source_paths = {path.resolve() for path in source_files}
    source_texts = {path.resolve(): texts.get(path.resolve(), "") for path in source_files}
    entrypoints, dependencies, manifests = package_information(root)
    inbound: dict[Path, set[Path]] = defaultdict(set)
    imported_packages: set[str] = set()
    python_modules = {
        python_module_name(path, root): path.resolve()
        for path in source_files
        if path.suffix.lower() == ".py"
    }

    for source in source_files:
        source = source.resolve()
        text = source_texts[source]
        if source.suffix.lower() in {".cjs", ".js", ".jsx", ".mjs", ".ts", ".tsx"}:
            for specifier in javascript_specifiers(text):
                resolved = resolve_javascript_import(source, specifier, source_paths)
                if resolved:
                    inbound[resolved].add(source)
                elif not specifier.startswith((".", "/", "#")):
                    imported_packages.add(package_name(specifier))
        elif source.suffix.lower() == ".py":
            for resolved in python_import_targets(source, text, root, python_modules):
                inbound[resolved].add(source)

    candidates: list[dict[str, Any]] = []
    for source in source_files:
        source = source.resolve()
        relative = relative_path(source, root)
        text = source_texts[source]
        if inbound[source] or is_protected_path(relative, text, entrypoints):
            continue
        mentions = referenced_outside_file(relative, source, texts)
        confidence = "medium" if mentions else "high"
        risk = "medium" if mentions else "low"
        evidence = [
            "No resolved static inbound import was found.",
            "The file is outside the detected entry-point and convention set.",
        ]
        caveats = [
            "Aliases, dynamic loading, reflection, external consumers, and incomplete framework detection can hide reachability."
        ]
        if mentions:
            evidence.append(f"Potential text references were found: {', '.join(mentions[:3])}.")
            caveats.append("Potential string reachability prevents high-confidence removal.")
        candidates.append(
            make_candidate(
                "orphan-file",
                relative,
                relative,
                confidence,
                risk,
                not mentions,
                source_line_count(text),
                source.stat().st_size,
                evidence,
                caveats,
            )
        )

    duplicate_groups: dict[str, list[Path]] = defaultdict(list)
    for source, text in source_texts.items():
        normalized = normalized_source(text)
        if source_line_count(normalized) >= 4 and len(normalized) >= 80:
            duplicate_groups[hashlib.sha256(normalized.encode()).hexdigest()].append(source)
    for matching_paths in duplicate_groups.values():
        if len(matching_paths) < 2:
            continue
        relatives = sorted(relative_path(path, root) for path in matching_paths)
        for duplicate in relatives[1:]:
            path = root / duplicate
            candidates.append(
                make_candidate(
                    "duplicate-file",
                    f"{duplicate} matches {relatives[0]}",
                    duplicate,
                    "high",
                    "medium",
                    False,
                    source_line_count(source_texts[path.resolve()]),
                    path.stat().st_size,
                    [f"Normalized non-empty content matches {relatives[0]} exactly."],
                    [
                        "Duplicate implementations can intentionally preserve module, runtime, ownership, or packaging boundaries."
                    ],
                )
            )

    searchable_text = "\n".join(
        text for path, text in texts.items() if path not in manifests and path.name != "package-lock.json"
    )
    for dependency, section, manifest_relative in sorted(dependencies):
        pattern = re.compile(rf"(?<![\w@/-]){re.escape(dependency)}(?![\w@-])")
        if dependency in imported_packages or pattern.search(searchable_text):
            continue
        candidates.append(
            make_candidate(
                "unused-dependency",
                f"{dependency} ({section} in {manifest_relative})",
                manifest_relative,
                "medium",
                "medium",
                False,
                0,
                0,
                ["No static JavaScript or TypeScript import or non-manifest text reference was found."],
                [
                    "Package scripts, CLIs, loaders, presets, peer relationships, and runtime configuration can use a dependency indirectly.",
                    "Manifest and lockfile changes require separate explicit approval.",
                ],
            )
        )

    export_pattern = re.compile(
        r"\bexport\s+(?:default\s+)?(?:async\s+)?(?:function|class|const|let|var|type|interface|enum)\s+([A-Za-z_$][\w$]*)"
    )
    all_source_text = "\n".join(source_texts.values())
    for source, text in source_texts.items():
        if source.suffix.lower() not in {".cjs", ".js", ".jsx", ".mjs", ".ts", ".tsx"}:
            continue
        for match in export_pattern.finditer(text):
            symbol = match.group(1)
            if len(symbol) < 4:
                continue
            remaining = all_source_text.replace(text, "", 1)
            if re.search(rf"\b{re.escape(symbol)}\b", remaining):
                continue
            candidates.append(
                make_candidate(
                    "unused-export",
                    f"{symbol} from {relative_path(source, root)}",
                    relative_path(source, root),
                    "medium",
                    "medium",
                    False,
                    0,
                    0,
                    ["No source reference to this exported symbol was found outside its defining file."],
                    [
                        "Public APIs, re-exports, generated declarations, templates, reflection, and downstream consumers can use exports without an in-repository reference."
                    ],
                    text[: match.start()].count("\n") + 1,
                )
            )

    commented_code = re.compile(
        r"(?m)(?:^\s*//.*(?:[;{}()]|\b(?:const|for|function|if|let|return|var)\b).*$\n?){4,}"
    )
    for source, text in source_texts.items():
        if source.suffix.lower() not in {".cjs", ".js", ".jsx", ".mjs", ".ts", ".tsx"}:
            continue
        for match in commented_code.finditer(text):
            block = match.group(0)
            candidates.append(
                make_candidate(
                    "commented-code",
                    f"Comment block in {relative_path(source, root)}",
                    relative_path(source, root),
                    "low",
                    "medium",
                    False,
                    source_line_count(block),
                    len(block.encode()),
                    ["A block of four or more code-like line comments was found."],
                    [
                        "The block may be documentation, an example, a protocol description, or an intentional workaround."
                    ],
                    text[: match.start()].count("\n") + 1,
                )
            )

    candidates.sort(
        key=lambda item: (CATEGORY_ORDER[item["category"]], item.get("path") or "", item["subject"])
    )
    for index, candidate in enumerate(candidates, start=1):
        candidate["id"] = f"CRT-{index:03d}"

    potential_by_path: dict[str, dict[str, Any]] = {}
    for candidate in candidates:
        if candidate["category"] not in {"orphan-file", "duplicate-file", "commented-code"}:
            continue
        path = candidate.get("path") or candidate["id"]
        existing = potential_by_path.get(path)
        if existing is None or candidate["loc"] > existing["loc"]:
            potential_by_path[path] = candidate

    return {
        "artifact_type": "code-rot-analysis",
        "schema_version": "1.0",
        "project_root": str(root),
        "generated_at": timestamp(),
        "scope": {
            "source_extensions": sorted(SOURCE_SUFFIXES),
            "excluded_directories": sorted(EXCLUDED_DIRECTORIES),
            "source_files": len(source_files),
            "source_loc": sum(source_line_count(text) for text in source_texts.values()),
            "source_bytes": sum(path.stat().st_size for path in source_files),
        },
        "summary": {
            "candidates": len(candidates),
            "proof_eligible": sum(candidate["proof_eligible"] for candidate in candidates),
            "potential_removable_loc": sum(
                candidate["loc"] for candidate in potential_by_path.values()
            ),
            "potential_removable_bytes": sum(
                candidate["bytes"] for candidate in potential_by_path.values()
            ),
            "by_category": {
                category: sum(candidate["category"] == category for candidate in candidates)
                for category in CATEGORY_ORDER
            },
        },
        "candidates": candidates,
        "limitations": [
            "Static analysis cannot prove the absence of dynamic, reflective, operational, platform-specific, or external use.",
            "Import resolution intentionally does not implement every alias, framework convention, or generated import.",
            "Unused dependencies and exports are leads, not deletion proof.",
            "The scan did not execute project code, package scripts, or dependency installers.",
            "Symlinked files are excluded from static scanning.",
        ],
    }


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("project", type=Path, help="Project root to inspect")
    parser.add_argument("output", type=Path, help="Path for analysis JSON")
    return parser.parse_args()


def main() -> int:
    args = parse_arguments()
    root = args.project.resolve()
    if not root.is_dir():
        print(f"error: Project root is not a directory: {root}", file=sys.stderr)
        return 2
    try:
        output = validate_artifact_outputs(
            [args.output], input_paths=[root], project_root=args.project
        )[0]
    except ArtifactSafetyError as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    try:
        analysis = analyze(root)
    except ValueError as error:
        print(f"error: {error}", file=sys.stderr)
        return 2
    try:
        publish_new_artifacts(
            [(output, (json.dumps(analysis, indent=2) + "\n").encode("utf-8"))],
            project_root=args.project,
        )
    except ArtifactSafetyError as error:
        print(f"error: {error}", file=sys.stderr)
        return 2
    print(f"Scanned {analysis['scope']['source_files']} source files.")
    print(f"Found {analysis['summary']['candidates']} candidates; {analysis['summary']['proof_eligible']} are proof-eligible.")
    print(f"Analysis: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
